spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/gate}
spring.datasource.username=${DATABASE_USERNAME:gate_user}
spring.datasource.password=${DATABASE_PASSWORD:userpassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:F1kGyQD9yhE3zBMTRXbSfpoVkiq3a5Y0U2OhLTnxzkX}
jwt.expiration=${JWT_EXPIRATION:172800000}

frontend.url=${FRONTEND_URL:http://localhost:5173,http://localhost:3000}
